### ISSUE TITLE
vite support

### ISSUE THREAD

**Issue by zigomir** [lmiller1990/vue-cypress-template#1]
hey!

congrats on huge component testing release – very intrigued!
you/cypress blog even teases there's a `vite` support for it but I've been struggling to find any references on how to set it up + struggling to guess how to set it up myself.

I'm sure this is coming sooner or later but I'd really like to try it out ;)

My `cypress/plugins/index.js` looks like this

```js
const { createServer } = require('vite')

module.exports = (on, config) => {
  on('dev-server:start', async (options) => {
    const server = await createServer()
    await server.listen()
    return server
  })

  return config
}
```

and I tried all possible variations of `return createServer()`, no `awaits` etc :)

The most I can get is this error:

```
npx cypress open-ct
ViteDevServer.app is deprecated. Use ViteDevServer.middlewares instead.
Error [TypeError]: Converting circular structure to JSON
```

Any help is much appreciated 🤞

**Comment by lmiller1990** [comment]
I just saw this. Sorry I missed this! 

Check this out: https://docs.cypress.io/guides/component-testing/framework-configuration#Vite-Based-Projects-Vue-React

Also there are many templates here, some with Vite: https://github.com/cypress-io/cypress-component-examples
